/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormBlocks: typeof import('./src/components/FormBlocks.vue')['default']
    FormBlocksRepeater: typeof import('./src/components/blocks/FormBlocksRepeater.vue')['default']
    FormBlocksRepeaterItem: typeof import('./src/components/blocks/FormBlocksRepeaterItem.vue')['default']
    FormGroupBlocks: typeof import('./src/components/blocks/FormGroupBlocks.vue')['default']
    FormInputsBlocks: typeof import('./src/components/blocks/FormInputsBlocks.vue')['default']
    HelloWorld: typeof import('./src/components/examples/HelloWorld.vue')['default']
  }
}
